### ISSUE TITLE
Реализовать действия для игрока

### ISSUE THREAD

**Issue by Dkoplik** [Dkoplik/effective-octo-potato-godot#3]
Обработки инпута тут нет, так как там нужен WebSocket и всякие приколы мультиплеера. Конкретно тут надо просто реализовать сами функции с возможными действиями игроков, которые уже будут вызываться из скрипта, отвечающего за обработку инпута игроков.

Для игроков нужны следующие функции:
- **Узнать позицию игрока в координатах тайлов** - сам игрок не является тайлом, поэтому надо соотносить его координаты на экране с координатами тайлов под ним
- **Поместить игрока в указаный тайл** - тайл задан координатами TileMapLayer, эта функция будет удобной для изначального спавна игроков + через неё можно будет сделать само перемещение.
- **Узнать текущее направление игрока** - возможно, сами направления можно сделать через какой-нибудь enum
- **Изменить направление игрока на заданное** - удобно будет для изначального спавна игроков + через эту функцию можно сделать сами повороты
- **Поворот игрока влево/вправо** - меняет направление игрока на соседнее соответствующим образом.
- **Шаг вперёд** - меняет координату игрока (в тайлах) на соседнюю в соответствии с его направлением.

**Comment by VadimDun** [comment]
#7
