### ISSUE TITLE
Создать базовые параметры тайлов

### ISSUE THREAD

**Issue by Dkoplik** [Dkoplik/effective-octo-potato-godot#5]
Самые-самые базовые параметры тайлов:
- Какие-то тайлы могут быть проходимыми, а какие-то нет (например, нельзя зайти в тайл с горой/стеной)
- Тайл может быть занят игроком. Другой игрок тогда не может зайти в этот тайл.
- Соответственно, перемещение должно учитывать эту особенность тайлов

**Comment by VadimDun** [comment]
ce5187c1c4d4e70247cf04dfd35b798b397179af
